@startuml

class FileOperator {
    - scoreDao: ScoreDaoImpl
    - path: String
    + FileOperator()
    + WriteFile():void
    - ReadFile():void
}

interface ScoreDao {
    + getAllScores(): List<Score>
    + findByName(String name): List<Score>
    + findByDifficulty(DIFFICULTY difficulty): List<Score>
    + doAdd(Date time, int score, String name, DIFFICULTY difficulty): void
    + doAdd(Score score): void
    + doDelete(Date time): void
}

class ScoreDaoImpl {
    + getAllScores(): List<Score>
    + findByName(String name): List<Score>
    + findByDifficulty(DIFFICULTY difficulty): List<Score>
    + doAdd(Date time, int score, String name, DIFFICULTY difficulty): void
    + doAdd(Score score): void
    + doDelete(Date time): void
    + doDelete(Score score): void
    + doDelete(int row): void
    + printOut(): void
    + parseString(String str): Score
}

class Score {
    - score: int
    - scoreTime: Date
    - userName: String
    - difficulty: DIFFICULTY
    + Score(int score, Date time, String name)
    + getScore(): int
    + getDifficulty(): DIFFICULTY
    + getScoreTime(): Date
    + printOut(): String
    + toString(): String
    - getDifficultyName(): String
}

ScoreDao <|-. ScoreDaoImpl
FileOperator .-> ScoreDao
ScoreDaoImpl -> Score

@enduml
